// Generated by CoffeeScript 1.6.3
(function() {
  var RepView, Representative;

  Representative = Backbone.Model.extend({});

  window.RepList = Backbone.Collection.extend({
    model: Representative,
    url: 'api/reps.php',
    initialize: function(state, zip) {
      if (zip) {
        return this.url = this.url + "?zip=" + state;
      } else {
        return this.url = this.url + "?state=" + state;
      }
    }
  });

  RepView = Backbone.View.extend({
    className: "col-md-3 representative-container",
    template: _.template($("#rep-template").html().trim()),
    render: function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    }
  });

  window.RepListView = Backbone.View.extend({
    el: "#reps-list",
    initialize: function(reps) {
      this.collection = reps;
      return this.render();
    },
    render: function() {
      this.collection.each(function(rep) {
        return this.renderRep(rep);
      }, this);
      return this;
    },
    renderRep: function(rep) {
      var repView;
      repView = new RepView({
        model: rep
      });
      return this.$el.append(repView.render().el);
    }
  });

}).call(this);
