// Generated by CoffeeScript 1.6.3
(function() {
  var RepList, RepView, Representative;

  Representative = Backbone.Model.extend({});

  RepList = Backbone.Collection.extend({
    model: Representative
  });

  RepView = Backbone.View.extend({
    template: _.template($("#rep-template").html().trim()),
    render: function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    }
  });

  window.RepListView = Backbone.View.extend({
    el: "#reps-list",
    initialize: function(reps) {
      this.collection = new RepList(reps);
      return this.render();
    },
    render: function() {
      this.collection.each(function(rep) {
        return this.renderRep(rep);
      }, this);
      return this;
    },
    renderRep: function(rep) {
      var repView;
      repView = new RepView({
        model: rep
      });
      return this.$el.append(repView.render().el);
    }
  });

}).call(this);
