// Generated by CoffeeScript 1.6.3
(function() {
  $(".fb").click(function() {
    return FB.login(function(response) {
      if (response.authResponse) {
        console.log('Welcome!  Fetching your information.... ');
        return FB.api('/me', function(response) {
          return console.log('Good to see you, ' + response.name + '.');
        });
      } else {

      }
    });
  });

}).call(this);
