// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $("#add-photo").click(function() {
      return FB.login(function(response) {
        if (response.authResponse) {
          console.log('Welcome!  Fetching your information.... ');
          return FB.api('/me', function(response) {
            return $.get('/api/insertUser.php', {
              uid: response.id
            }, function() {
              var count;
              $("#fb-images-container").prepend("<div class='clip'><div class='overlay'></div><img src='http://graph.facebook.com/" + response.id + "/picture?type=large'/></div>");
              count = parseInt($("#count").text(), 10);
              return $("#count").text(count + 1);
            });
          });
        }
      });
    });
  });

}).call(this);
